const constants = {
    FETCH_EMPLOYEES: 'FETCH_EMPLOYEES',
    FETCH_EMPLOYEE: 'FETCH_EMPLOYEE',
    CREATE_EMPLOYEE: 'CREATE_EMPLOYEE',
    EDIT_EMPLOYEE: 'EDIT_EMPLOYEE',
    DELETE_EMPLOYEE: 'DELETE_EMPLOYEE'

}

export default constants;